language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: ngvikings-2019
  token:
    secure: jJa+aHf1mRzBuw0kk0Caacx8xkhYX86n3es360RQtTFNc2CUXt++6VaxUFSnzd9pD0xEoJxsOwLgjCZo3R7reUlDxwLhI6WKh1UythhRfXT+wbYdKubHd+L2M5X2Bwwmbzq5B1+wJ96nZUW2B8metbmgraJdAT7dhEGjyXJsuvRdq/aDR6mgbW+XWeid/4GfckOK52Ew7NpwRBuOzbYCG3PFxCNaNM+y0omtDEPt1hGCZbHhFnTie4PVdaXLYK6u54YKm/ofHVgjsnuxNpdnzt8WyIXqfNHiqC7xIp8GKklHHzLrOL8X9QW8swBOSPipxCSW9kXlXZojitAl/HIqCWRJtsjvLfFY/BkPM3MtIwhLNO0GVky73wih6kIcUXjYJ2w1nUZeVDx2lOlvb8sJziV9nEzGEdFHBJJYdpNirkgBXRFPfLRVTFNhyf6Cj30lnuW+XMBLh/xwciNqsfZajxvlN/4Vwf0xqz3A8U65Bmskm0uliE3QExNUcaZB8Dbz4kGej1a5rz7SFn+QYzLMXb2hkOlhSoywwLfTSs7sNgYuepPdaVEWQPz/UHr8KKavSFpvVUqM05Lm2+lvDbUUhSfcCAhUPEDURql6duwR8M9vynsTBG0BCk1+rSvHU+9HU0ZeXgZ3VmqwfHyLqDq30lZ+m6CHLfXydwzIQIEmArA=