language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: ngvikings-2019
  token:
    secure: PijqQ0lSksqEePcm/s9dOjaMfALGvchYEwU1ov7GQZMqnCGyUIVkCLJAj/JdXHsLcZz+gDZr7IZcLEc7pvTgF0hbwUiZygyC+wDozS/4UHxzxM8nJiGjj13dkNWzJtYt4Br8R5FVZq8iIqhtFMihB3klseZl+q4WWmhXp31IfGsxXxItyX5mDSrpkh4FhyCd/4JOoEOaaxrc9XNJ1s0JF9MggNpEUwkdqf0q4xShInMB82bJuvyUNmsfmrkHO2RM2at26OnPQ3UDEKe1d/yPeFh2jUGa7cJdb0e9ZUz5GN9Yu8w9WjSKPSQdePJpC7Jk06mUHIkKmO4z/VqDVMBF1y4aEKYhB7Z/dya3S9sRi7hXStsPXqcVeSvMaLTru32KIv5lELK4yRT9OZkJ7+LSM6JiM5G6HENDviE2HPZCmCS1r9xqTUxMLl2bw9PhTOwyxj9IRUTSY+fn8XVaGFf15ETyLNJBd6C9tXP6yWKGJFRAV0tCf1e7doVotTCFFBJH608Rn9xf3AC8lqRJsfQ1CLIRNLCy5RAb+1pSAMOgu0zszOReqTWAFogG4sEmaHWXyPx5e4haLbe5r9JMksTLOqj9EUPLYCEb8a+I9yKSKiIaScye/Kx1nvtV3YrNogzVee8EqYashMiyMJBwGstoj4RFlOy1lqT5Awr859GDHes=